<a href="https://colab.research.google.com/github/gloriabee/ML_Engineer_Journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is Numpy?



*   Python library for creating N-dimensional arrays
*   Ability to quickly broadcast functions
*   Built-in linear algebra, statistical distributions, trigonometric, and random number capabilities



## Why use Numpy?



*   While NumPy structures look similar to standard Python lists, they are much more efficient!
*   The broadcasting capabilities are also extremely useful for quickly applying functions to our data sets.



## Numpy Arrays

In [3]:
import numpy as np

In [1]:
mylist=[1,2,3]
type(mylist)

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr=np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [13]:
my_matrix= [[1,2,3],[4,5,6],[7,8,9]]
type(my_matrix)

list

In [16]:
my_matrix=np.array(my_matrix)
type(my_matrix)
my_matrix.shape

(3, 3)

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [35]:
len(np.linspace(0,5,21))

21

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.random.rand(5,2)

array([[0.5123519 , 0.9847533 ],
       [0.07450119, 0.3321475 ],
       [0.30924314, 0.38640974],
       [0.13881798, 0.83536443],
       [0.06671396, 0.30322884]])

In [45]:
np.random.randn(2,3) #normal distribution

array([[-1.41116196, -0.50124812,  0.51218414],
       [ 2.10014367,  0.14094045, -1.6665673 ]])

In [51]:
np.random.randint(0,101,10)

array([20, 86, 91, 25,  0,  3, 56, 82, 31, 23])

In [56]:
np.random.seed(101)
np.random.rand(2)

array([0.51639863, 0.57066759])

In [57]:
np.random.rand(4)

array([0.02847423, 0.17152166, 0.68527698, 0.83389686])

In [62]:
arr=np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
ranarr=np.random.randint(0,101,10)
ranarr

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [65]:
ranarr.max()

np.int64(83)

In [66]:
ranarr.min()

np.int64(8)

In [67]:
ranarr.argmax()

np.int64(1)

In [68]:
ranarr.argmin()

np.int64(2)

In [69]:
ranarr.dtype

dtype('int64')

In [71]:
arr.shape

(25,)

In [73]:
arr= arr.reshape(5,5)
arr.shape

(5, 5)

### Exercise 1

**TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.**

In [75]:
myarray= np.linspace(0,10,101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## Numpy Indexing and Selection

In [77]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr[1:5]

array([1, 2, 3, 4])

In [83]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [84]:
arr[:5]

array([0, 1, 2, 3, 4])

In [85]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
#Broadcasting and reassign it
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [91]:
arr= np.arange(0,11)
slice_of_arr=arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [93]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [94]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [99]:
arr_copy=arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [100]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [103]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
arr_2d.shape

(3, 3)

In [107]:
arr_2d[2]

np.int64(40)

In [110]:
arr_2d[1,1]
arr_2d[1][1]

np.int64(25)

In [113]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [115]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [122]:
bool_arr= arr>4
arr[bool_arr]

arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### Exercise 2

 TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
 NOTE: Many different ways to do this! Your final answer should be an integer.

In [123]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [128]:
len(dice_rolls[dice_rolls>2])

19

## Numpy Operations

In [134]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [136]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [137]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [138]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [139]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [141]:
arr/arr

<ipython-input-141-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [144]:
1/ arr

<ipython-input-144-d25465d7253e>:1: RuntimeWarning: divide by zero encountered in divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [145]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [146]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [147]:
np.log(arr)

<ipython-input-147-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [148]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
arr.sum()

np.int64(45)

In [150]:
arr.max()

np.int64(9)

In [151]:
arr.mean()

np.float64(4.5)

In [152]:
arr.var()

np.float64(8.25)

In [153]:
arr.std()

np.float64(2.8722813232690143)

In [160]:
arr2d= np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
arr2d.shape

(5, 5)

In [159]:
arr2d.sum()

np.int64(300)

In [161]:
arr2d.sum(axis=0) # addition by column

array([50, 55, 60, 65, 70])

In [163]:
arr2d.sum(axis=1) # addition by row

array([ 10,  35,  60,  85, 110])

## Exercise

In [164]:
import numpy as np

In [170]:
# Create an array of 10 zeros
zeroarr= np.zeros(10)
zeroarr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [172]:
# create an array of 10 ones
onearr= np.ones(10)
onearr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [176]:
# create an array of 10 fives
fivearr= np.ones(10)*5
fivearr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [178]:
# create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [181]:
# create an array of all even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [193]:
# create a 3*3 matrix with values ranging from o to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [184]:
# create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [191]:
# use NumPy to generate a random number between 0 and 1.
np.random.rand(1)

array([0.51786747])

In [192]:
# use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution.
np.random.randn(25)

array([ 2.60596728,  0.68350889,  0.30266545,  1.69372293, -1.70608593,
       -1.15911942, -0.13484072,  0.39052784,  0.16690464,  0.18450186,
        0.80770591,  0.07295968,  0.63878701,  0.3296463 , -0.49710402,
       -0.7540697 , -0.9434064 ,  0.48475165, -0.11677332,  1.9017548 ,
        0.23812696,  1.99665229, -0.9932635 ,  0.1967995 , -1.13664459])

In [203]:
# Create the following matrix
arr=np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [205]:
# Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])