<a href="https://colab.research.google.com/github/gloriabee/ML_Engineer_Journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is Numpy?



*   Python library for creating N-dimensional arrays
*   Ability to quickly broadcast functions
*   Built-in linear algebra, statistical distributions, trigonometric, and random number capabilities



## Why use Numpy?



*   While NumPy structures look similar to standard Python lists, they are much more efficient!
*   The broadcasting capabilities are also extremely useful for quickly applying functions to our data sets.



## Numpy Arrays

In [3]:
import numpy as np

In [4]:
mylist=[1,2,3]
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr=np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix= [[1,2,3],[4,5,6],[7,8,9]]
type(my_matrix)

list

In [10]:
my_matrix=np.array(my_matrix)
type(my_matrix)
my_matrix.shape

(3, 3)

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [16]:
len(np.linspace(0,5,21))

21

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(5,2)

array([[0.27722508, 0.39877996],
       [0.20943651, 0.29656373],
       [0.70791474, 0.61421157],
       [0.70049963, 0.45299378],
       [0.40382608, 0.40509496]])

In [19]:
np.random.randn(2,3) #normal distribution

array([[-1.09606993,  0.76351139,  0.26930217],
       [-2.24561801,  1.88957185, -1.91408501]])

In [20]:
np.random.randint(0,101,10)

array([19, 81, 76,  0, 24, 92, 79,  8, 65, 60])

In [21]:
np.random.seed(101)
np.random.rand(2)

array([0.51639863, 0.57066759])

In [22]:
np.random.rand(4)

array([0.02847423, 0.17152166, 0.68527698, 0.83389686])

In [23]:
arr=np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr=np.random.randint(0,101,10)
ranarr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [25]:
ranarr.max()

np.int64(93)

In [26]:
ranarr.min()

np.int64(4)

In [27]:
ranarr.argmax()

np.int64(8)

In [28]:
ranarr.argmin()

np.int64(0)

In [29]:
ranarr.dtype

dtype('int64')

In [30]:
arr.shape

(25,)

In [31]:
arr= arr.reshape(5,5)
arr.shape

(5, 5)

### Exercise 1

**TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.**

In [32]:
myarray= np.linspace(0,10,101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## Numpy Indexing and Selection

In [33]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[:5]

array([0, 1, 2, 3, 4])

In [37]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
#Broadcasting and reassign it
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
arr= np.arange(0,11)
slice_of_arr=arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [40]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [41]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [42]:
arr_copy=arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [43]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [44]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
arr_2d.shape

(3, 3)

In [46]:
arr_2d[2]

array([35, 40, 45])

In [47]:
arr_2d[1,1]
arr_2d[1][1]

np.int64(25)

In [48]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [49]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
bool_arr= arr>4
arr[bool_arr]

arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### Exercise 2

 TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
 NOTE: Many different ways to do this! Your final answer should be an integer.

In [52]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [53]:
len(dice_rolls[dice_rolls>2])

19

## Numpy Operations

In [54]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [57]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
arr/arr

<ipython-input-60-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [61]:
1/ arr

<ipython-input-61-d25465d7253e>:1: RuntimeWarning: divide by zero encountered in divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [62]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [63]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [64]:
np.log(arr)

<ipython-input-64-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [65]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr.sum()

np.int64(45)

In [67]:
arr.max()

np.int64(9)

In [68]:
arr.mean()

np.float64(4.5)

In [69]:
arr.var()

np.float64(8.25)

In [70]:
arr.std()

np.float64(2.8722813232690143)

In [71]:
arr2d= np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
arr2d.shape

(5, 5)

In [73]:
arr2d.sum()

np.int64(300)

In [74]:
arr2d.sum(axis=0) # addition by column

array([50, 55, 60, 65, 70])

In [75]:
arr2d.sum(axis=1) # addition by row

array([ 10,  35,  60,  85, 110])

## Exercise

In [76]:
import numpy as np

In [77]:
# Create an array of 10 zeros
zeroarr= np.zeros(10)
zeroarr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
# create an array of 10 ones
onearr= np.ones(10)
onearr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
# create an array of 10 fives
fivearr= np.ones(10)*5
fivearr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [80]:
# create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [81]:
# create an array of all even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [82]:
# create a 3*3 matrix with values ranging from o to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
# create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
# use NumPy to generate a random number between 0 and 1.
np.random.rand(1)

array([0.1818924])

In [85]:
# use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution.
np.random.randn(25)

array([-0.16814492, -0.10806726,  1.51144365,  0.68346094,  0.93991936,
       -1.1349718 , -0.63579197,  0.02515971, -0.27306951, -0.31589962,
        0.00858304,  0.20530702,  1.58917569,  0.53322084,  0.85734924,
        0.08707633, -0.39746171,  1.26168798,  0.43333132, -0.1366137 ,
        0.88213984, -0.37781124,  0.1466388 ,  1.26912178,  0.30788108])

In [86]:
# Create the following matrix
arr=np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [87]:
# Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [88]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [89]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [93]:
mat[3,-1]

np.int64(20)

In [100]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [101]:
mat[-1]

array([21, 22, 23, 24, 25])

In [102]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
# Give the sum of all the values in mat
mat.sum()

np.int64(325)

In [104]:
# Get the standard deviation of the values in mat
mat.std()

np.float64(7.211102550927978)

In [107]:
# Get the sum of all the columns in mat
mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

## Bonus Question

We worked a lot with random data with numpy. but is there a way we can insure that we always get the same random numbers?

In [110]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])

In [111]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])